#!/usr/bin/env python3
"""Write a copy of the home page at every URL the site can be linked to.

GitHub Pages serves files, not routes, so /music/the-conversation has to exist
as a file or it is a 404. This writes one per section and one per release, each
a copy of index.html with its own title and preview tags, so a link to a record
shows that record when it is pasted somewhere.

Run from the repo root, by the deploy workflow, before the upload. Nothing it
writes is committed.

    python3 build_routes.py            # write the routes
    python3 build_routes.py --clean    # remove them again
"""
import datetime
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).parent
INDEX = ROOT / 'index.html'
SITE = 'https://lockslip.band'

# The marker that says a directory is ours to delete on --clean, since these sit
# next to real directories like press/ and plugin/.
STAMP = '<!-- generated by build_routes.py -->'


def sections(html):
    """Section ids, read from the markup so the two cannot drift."""
    return re.findall(r'<section id="([a-z0-9-]+)"', html)


def releases():
    data = json.loads((ROOT / 'content' / 'releases.json').read_text())
    return [r for r in data.get('releases', []) if not r.get('hidden')]


def meta(title, description, image, url):
    """og and twitter tags, so a pasted link previews as the thing it points at."""
    tags = [
        STAMP,
        f'<meta property="og:title" content="{title}">',
        f'<meta property="og:description" content="{description}">',
        f'<meta property="og:url" content="{url}">',
        '<meta property="og:type" content="music.album">',
        '<meta name="twitter:card" content="summary_large_image">',
    ]
    if image:
        tags.append(f'<meta property="og:image" content="{image}">')
    return '\n    '.join(tags)


def write(path, html, title, description, image, url):
    out = ROOT / path
    out.mkdir(parents=True, exist_ok=True)

    page = html.replace('</title>', '</title>\n    ' + meta(title, description, image, url), 1)
    page = re.sub(r'<title>.*?</title>', f'<title>{title}</title>', page, count=1)
    (out / 'index.html').write_text(page)
    return out


def clean():
    removed = 0
    for index in ROOT.glob('*/index.html'):
        if STAMP in index.read_text():
            shutil.rmtree(index.parent)
            removed += 1
    for index in ROOT.glob('*/*/index.html'):
        if index.exists() and STAMP in index.read_text():
            shutil.rmtree(index.parent)
            removed += 1
    print(f'removed {removed} generated routes')


def sitemap(paths):
    """Every URL the site has, so a crawler is told rather than left to guess.

    The homepage carried a rendering error into Google's index once, and without
    a sitemap there was nothing to point at to get it looked at again."""
    today = datetime.date.today().isoformat()
    urls = ''.join(
        f'\n  <url><loc>{SITE}/{path}</loc><lastmod>{today}</lastmod></url>'
        for path in [''] + paths)
    (ROOT / 'sitemap.xml').write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
        f'{urls}\n</urlset>\n')
    return len(paths) + 1


def main():
    if '--clean' in sys.argv:
        return clean()

    html = INDEX.read_text()
    written = []

    for section in sections(html):
        written.append(write(
            section, html,
            f'Lockslip - {section.title()}',
            'Lockslip, metallic hardcore from Los Angeles.',
            f'{SITE}/assets/releases/2026-lp1-cover.jpg',
            f'{SITE}/{section}'))

    for release in releases():
        cover = release.get('coverImage')
        written.append(write(
            f'music/{release["id"]}', html,
            # The EP's title already says Lockslip.
            release["title"] if release["title"].lower().startswith('lockslip')
                else f'Lockslip - {release["title"]}',
            (release.get('description') or '').split('.')[0][:200],
            f'{SITE}/{cover}' if cover else '',
            f'{SITE}/music/{release["id"]}'))

    for path in written:
        print('wrote', path.relative_to(ROOT) / 'index.html')

    print(f'wrote sitemap.xml with {sitemap([str(p.relative_to(ROOT)) for p in written])} urls')


if __name__ == '__main__':
    main()
